// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteApp.Data;

#nullable disable

namespace SQLiteApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SQLiteApp.Data.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrencyRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyName = "$",
                            CurrencyRate = 29.0,
                            RateDate = new DateTime(2023, 12, 9, 16, 27, 26, 988, DateTimeKind.Local).AddTicks(4420)
                        },
                        new
                        {
                            Id = 2,
                            CurrencyName = "€",
                            CurrencyRate = 31.0,
                            RateDate = new DateTime(2023, 12, 9, 16, 27, 26, 988, DateTimeKind.Local).AddTicks(4470)
                        },
                        new
                        {
                            Id = 3,
                            CurrencyName = "£",
                            CurrencyRate = 36.0,
                            RateDate = new DateTime(2023, 12, 9, 16, 27, 26, 988, DateTimeKind.Local).AddTicks(4480)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
